---
- name: "Install Postgres"
  apt:
    name: postgresql, python-psycopg2
    state: present
  become: true

- name: "Start Postgres"
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: "Create master db"
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    encoding: "UTF-8"
  become: true
  become_user: "{{ db_user }}"
  with_items: "{{ db_name }}"

- name: "Give role to unix acc"
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ unix_user }}"
    priv: "ALL"
  become: true
  become_user: "{{ db_user }}"
